import mongoose, { Schema } from "mongoose";

const memberSchema = new Schema({
  fields: {
    step1: {
      f1: { type: String },
      f2: { type: String },
      f4: { type: String },
      f5: { type: String },
      f6: { type: String },
      f7: { type: String },
      f8: { type: String },
      f9: { type: String },
    },
    step2: {
      f10: { type: String },
      f11: { type: String },
      f12: { type: String },
      f13: { type: String },
      f14: { type: String },
    },
    step3: {
      f15: { type: String },
      f16: { type: String },
      f17: { type: String },
      f18: { type: String },
      f19: { type: String },
    },
    step4: {
      f20: { type: String },
      f21: { type: String },
      f22: { type: String },
      f23: { type: String },
      f24: { type: String },
      f25: { type: String },
      f26: { type: String },
      f27: { type: String },
      f28: { type: String },
      f29: { type: String },
      f30: { type: String },
      f31: { type: String },
      f32: { type: String },
      f33: { type: String },
      f34: { type: String },
      f35: { type: String },
      f36: { type: String },
    },
    step5: {
      f37: { type: String },
      f38: { type: String },
      f39: { type: String },
      f40: { type: String },
      f41: { type: String },
      f42: { type: String },
      f43: { type: String },
      f44: { type: String },
      f45: { type: String },
      f46: { type: String },
      f47: { type: String },
      f48: { type: String },
      f49: { type: String },
      f50: { type: String },
      f51: { type: String },
      f52: { type: String },
      f53: { type: String },
      f54: { type: String },
      f55: { type: String },
      f56: { type: String },
      f57: { type: String },
      f58: { type: String },
      f59: { type: String },
      f60: { type: String },
    },
    step6: {
      f61: { type: String },
      f62: { type: String },
      f63: { type: String },
      f64: { type: String },
      f65: { type: String },
      f66: { type: String },
      f67: { type: String },
      f68: { type: String },
      f69: { type: String },
      f70: { type: String },
      f71: { type: String },
      f72: { type: String },
      f73: { type: String },
      f74: { type: String },
      f75: { type: String },
      f76: { type: String },
      f77: { type: String },
      f78: { type: String },
      f79: { type: String },
      f80: { type: String },
      f81: { type: String },
      f82: { type: String },
      f83: { type: String },
      f84: { type: String },
      f85: { type: String },
      f86: { type: String },
      f87: { type: String },
      f88: { type: String },
      f89: { type: String },
      f90: { type: String },
      f91: { type: String },
      f92: { type: String },
      f93: { type: String },
      f94: { type: String },
      f95: { type: String },
      f96: { type: String },
      f97: { type: String },
      f98: { type: String },
    },
    step7: {
      f99: { type: String },
      f100: { type: String },
      f101: { type: String },
      f102: { type: String },
      f103: { type: String },
      f104: { type: String },
      f105: { type: String },
      f106_1: { type: String },
      f106_2: { type: String },
      f107_1: { type: String },
      f107_2: { type: String },
      f107_3: { type: String },
      f108: { type: String },
      f109: { type: String },
    },
    step8: {
      f110: { type: String },
      f111_1: { type: String },
      f112_1: { type: String },
      f113_1: { type: String },
      f111_2: { type: String },
      f112_2: { type: String },
      f113_2: { type: String },
    },
    step9: {
      f114: { type: String },
      f115: { type: String },
      f116_1: { type: String },
      f116_2: { type: String },
      f116_3: { type: String },
      f117_1: { type: String },
      f118_1: { type: String },
      f117_2: { type: String },
      f118_2: { type: String },
      f119: { type: String },
      f120: { type: String },
      f121: { type: String },
      f122_1: { type: String },
      f122_2: { type: String },
      f122_3: { type: String },
      f123: { type: String },
      f124: { type: String },
      f125: { type: String },
      f126: { type: String },
    },
    step10: {
      f127: { type: String },
      f128: { type: String },
      f129: { type: String },
      f130_1: { type: String },
      f130_2: { type: String },
      f130_3: { type: String },
      f131: { type: String },
      f132: { type: String },
      f133: { type: String },
      f134: { type: String },
      f135: { type: String },
      f136: { type: String },
      f137: { type: String },
      f138: { type: String },
      response: { type: String },
      reason: { type: String },
    },
    step11: {
      h1: { type: String },
      h2: { type: String },
      h3: { type: String },
      h4: { type: String },
      h5: { type: String },
      h6: { type: String },
      h7: { type: String },
      h8: { type: String },
      h9: { type: String },
      h10: { type: String },
      h11: { type: String },
      h12: { type: String },
      h13: { type: String },
      h14: { type: String },
      h15: { type: String },
      h16: { type: String },
      h17: { type: String },
      h18: { type: String },
      h19: { type: String },
      id_code1: { type: String },
      id_code2: { type: String },
    },
    ww_hh: { type: String },
    ww_pop: { type: String },
    re_f10: { type: String },
    re_f14: { type: String },
    re_occ: { type: String },
    re_ind: { type: String },
    dif_2_4: { type: String },
    dif_5_17: { type: String },
    dif_18: { type: String },
  },
  iden: { type: String, required: true },
  file_id: { type: Schema.Types.ObjectId, ref: "File", required: true },
  status: { type: String, required: true },
});

export default mongoose.model("Member", memberSchema);
